name: OWASP ZAP Integration with GitHub Actions - Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web applicationconfigure permissions in Actions settings
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set permissions
        run: |
          mkdir /tmp/zap
          chmod a+w /tmp/zap
          ls -la /tmp/zap

      - name: ZAP Scan
        run: docker run --rm -v $(pwd):/zap/wrk -t zaproxy/zap-stable zap-full-scan.py -t http://testphp.vulnweb.com/ -J report.json -I
        working-directory: /tmp/zap

      - name: View files
        run: |
          cat report.json
        working-directory: /tmp/zap

      - name: Push report to CSPM panel
        run: |
          curl --location --request POST 'https://${{ env.endpoint }}/api/v1/artifact/?tenant_id=${{ env.tenant_id }}&data_type=ZAP&label_id=dast&save_to_s3=false' --header 'Tenant-Id: ${{ env.tenant_id }}' --header 'Authorization: Bearer ${{ env.token }}' --form 'file=@report.json'
        env:
          token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzNjUzMzczLCJqdGkiOiI4NjgxMWFiN2QyMjY0Y2U4YmFmNzY0Mzg3YTUzZTdjMSIsImlzcyI6ImNzcG0uc3RhZ2UuYWNjdWtub3guY29tIn0.M649_XWwAeC9udSQOIQV9f4yPGLfHwJn99JKRpvq5OP9Mxgb4PV_oyfsLf3HvpAaQpR7MCTwf5CT8MeU8q-SxFYqH-JBevnnHOsfwPGBPFemmYib7Q0JSempY5-eYTTFRlGKD0MuKY7kMk_HsScF_Bstdpd6ugyVAdHwY4WHOHzuK8Mn3nUJwcrD2Bzm2tgYBe38IX5DA3f2tvYCex2oWOl-xhNPUKG86Obrl4qpOAwjRMgvICdE43BffixPJLC4WUHYVkg6lwk6cx76dpK69w0VeA0CAa7HpdUZnchxZKqweM3G3gObOjnbPRnE03Ny7yk2E1cdqR8sylCq8f9g3w"
          endpoint: "cspm.stage.accuknox.com"
          tenant_id: "5088"
        working-directory: /tmp/zap
