name: OWASP ZAP Integration with GitHub Actions - Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web applicationconfigure permissions in Actions settings
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set permissions
        run: |
          mkdir /tmp/zap
          chmod a+w /tmp/zap
          ls -la /tmp/zap

      - name: ZAP Scan
        run: docker run --rm -v $(pwd):/zap/wrk -t zaproxy/zap-stable zap-full-scan.py -t http://testphp.vulnweb.com/ -J report.json -I
        working-directory: /tmp/zap

      - name: View files
        run: |
          cat report.json
        working-directory: /tmp/zap

      - name: Push report to CSPM panel
        run: |
          curl --location --request POST 'https://${{ env.endpoint }}/api/v1/artifact/?tenant_id=${{ env.tenant_id }}&data_type=ZAP&label_id=zaptest&save_to_s3=false' --header 'Tenant-Id: ${{ env.tenant_id }}' --header 'Authorization: Bearer ${{ env.token }}' --form 'file=@report.json'
        env:
          token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4MzA4NjY3LCJqdGkiOiJjNWI5NTMzODM2ZGE0ZjVhODhkYjQ2MjhkZjkwOTQwZCIsImlzcyI6ImNzcG0uc3RhZ2UuYWNjdWtub3guY29tIn0.d2juxKrK6-D8B2IuXV2btQ_eOrKqjf6dGU4-oYK591_62hoIYG5azgDfMy_bbTk2B1SFUmg6fyUVQNnL8O8R4cL1uDe-TGcfa63dPZjoHOBk8K5swN_djepkrMZoB1ppDT-CIiBaEuClTaqQmL9N5C57epvkN7jawbft2WUVuhuE2B_3EwLOFhZKcqC6-jnJ91m9udYSzntpNneBhj5MoVd4mBOqLR05p_E9c2qTr21Ios-DhdGiZE783priya_glZtRYmeU_dg2_KtQN1Tmg_wXTlUc7-oOToPaoOtV1zfVtOu0i9CxvV8Lhg9VsmtN03bvWd0S3gyX1vD2letSLg"
          endpoint: "cspm.stage.accuknox.com"
          tenant_id: "4"
        working-directory: /tmp/zap
